import { useMemo, useState } from "react";
import { calculateRemainingDays } from "../../api/allocations.js";
import { calculateRequestedDays } from "../../api/timeOff.js";

export default function TimeOffRequestForm({ initialValues, employees, types, allocations, onSubmit, onCancel, submitting, serverError }) {
  const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState({}); const inputClass = "mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200";
  const allocation = useMemo(() => allocations.find((item) => item.employeeId === values.employeeId && item.timeOffTypeId === values.timeOffTypeId && item.status === "Active" && (!values.startDate || item.validFrom <= values.startDate) && (!values.endDate || item.validUntil >= values.endDate)), [allocations, values.employeeId, values.timeOffTypeId, values.startDate, values.endDate]);
  const available = allocation ? calculateRemainingDays(allocation) : null; const duration = calculateRequestedDays(values.startDate, values.endDate);
  function change(event) { const next = { ...values, [event.target.name]: event.target.value }; if (event.target.name === "employeeId") { const employee = employees.find((item) => item.id === event.target.value); if (employee) next.employeeName = employee.fullName; } if (event.target.name === "timeOffTypeId") { const type = types.find((item) => item.id === event.target.value); if (type) next.timeOffTypeName = type.name; } setValues(next); setErrors((current) => ({ ...current, [event.target.name]: "" })); }
  function submit(event) { event.preventDefault(); const next = {}; if (!values.employeeId) next.employeeId = "Employee is required."; if (!values.timeOffTypeId) next.timeOffTypeId = "Time off type is required."; if (!values.startDate) next.startDate = "Start date is required."; if (!values.endDate) next.endDate = "End date is required."; if (values.startDate && values.endDate && values.endDate < values.startDate) next.endDate = "End date cannot be earlier than start date."; if (available !== null && duration > available) next.endDate = `Requested duration exceeds the available balance of ${available} days.`; setErrors(next); if (!Object.keys(next).length) onSubmit({ ...values, availableBalance: available ?? values.availableBalance ?? null }); }
  return <form onSubmit={submit} noValidate className="overflow-hidden border border-slate-200 bg-white shadow-sm">{serverError && <div role="alert" className="border-b border-red-200 bg-red-50 px-5 py-3 text-sm text-red-700">{serverError}</div>}<div className="grid gap-x-6 gap-y-5 p-5 sm:grid-cols-2 sm:p-6"><Select label="Employee" name="employeeId" value={values.employeeId} onChange={change} error={errors.employeeId} className={inputClass} placeholder="Select employee" options={employees.map((employee) => [employee.id, `${employee.fullName} (${employee.employeeId})`])} /><Select label="Time off type" name="timeOffTypeId" value={values.timeOffTypeId} onChange={change} error={errors.timeOffTypeId} className={inputClass} placeholder="Select time off type" options={types.filter((type) => type.status === "Active" || type.id === values.timeOffTypeId).map((type) => [type.id, type.name])} /><Field label="Start date" name="startDate" type="date" value={values.startDate} onChange={change} error={errors.startDate} className={inputClass} /><Field label="End date" name="endDate" type="date" value={values.endDate} onChange={change} error={errors.endDate} className={inputClass} /><div className="grid grid-cols-2 gap-4 border border-slate-200 bg-slate-50 p-3 sm:col-span-2"><Metric label="Requested duration" value={duration ? `${duration} days` : "—"} /><Metric label="Available allocation" value={available === null ? "No matching balance" : `${available} days`} /></div><label className="text-sm font-medium text-slate-700 sm:col-span-2">Reason <span className="font-normal text-slate-400">(optional)</span><textarea name="reason" rows="4" value={values.reason} onChange={change} className={inputClass} /></label></div><div className="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-5 py-4 sm:px-6"><button type="button" onClick={onCancel} className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancel</button><button type="submit" disabled={submitting} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-60">{submitting ? "Saving…" : "Submit request"}</button></div></form>;
}
function Metric({ label, value }) { return <div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-slate-900">{value}</p></div>; } function Field({ label, name, type, value, onChange, error, className }) { return <label className="text-sm font-medium text-slate-700">{label} <Required /><input name={name} type={type} value={value} onChange={onChange} className={className} aria-invalid={Boolean(error)} /><Error text={error} /></label>; } function Select({ label, name, value, onChange, error, className, placeholder, options }) { return <label className="text-sm font-medium text-slate-700">{label} <Required /><select name={name} value={value} onChange={onChange} className={className}><option value="">{placeholder}</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select><Error text={error} /></label>; } function Required() { return <span className="text-red-600">*</span>; } function Error({ text }) { return text ? <span className="mt-1 block text-xs text-red-600">{text}</span> : null; }
