import { Link } from "react-router-dom";
import { calculateRequestedDays } from "../../api/timeOff.js";
import TimeOffStatusBadge from "./TimeOffStatusBadge.jsx";

const dateFormatter = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }); const date = (value) => dateFormatter.format(new Date(`${value}T00:00:00`));
export default function TimeOffTable({ requests }) {
  const headings = ["Request ID", "Employee", "Time off type", "From", "To", "Duration", "Status", "Actions"];
  return <div className="overflow-x-auto"><table className="w-full min-w-[940px] divide-y divide-slate-200 text-left text-sm lg:min-w-0"><thead className="bg-slate-50 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><tr>{headings.map((heading) => <th key={heading} scope="col" className="whitespace-nowrap px-4 py-3 first:pl-5 last:pr-5">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 bg-white">{requests.map((request) => <tr key={request.id} className="transition-colors hover:bg-slate-50"><td className="whitespace-nowrap px-4 py-3 pl-5 font-semibold text-slate-700">{request.id}</td><td className="min-w-44 px-4 py-3"><Link to={`/employees/${request.employeeId}`} className="font-semibold text-slate-900 hover:underline">{request.employeeName}</Link><p className="text-xs text-slate-500">{request.employeeId}</p></td><td className="px-4 py-3 font-medium text-slate-700">{request.timeOffTypeName}</td><td className="whitespace-nowrap px-4 py-3 text-slate-600">{date(request.startDate)}</td><td className="whitespace-nowrap px-4 py-3 text-slate-600">{date(request.endDate)}</td><td className="whitespace-nowrap px-4 py-3 font-semibold tabular-nums text-slate-800">{calculateRequestedDays(request.startDate, request.endDate)} d</td><td className="whitespace-nowrap px-4 py-3"><TimeOffStatusBadge status={request.status} /></td><td className="whitespace-nowrap px-4 py-3 pr-5"><div className="flex gap-3 font-semibold"><Link to={`/timeoff/${request.id}`} className="text-slate-700 hover:underline">View</Link><Link to={`/timeoff/${request.id}/edit`} className="text-blue-700 hover:underline">Edit</Link></div></td></tr>)}</tbody></table></div>;
}
