import { useState } from "react";

export default function TimeOffTypeForm({ initialValues, onSubmit, onCancel, submitting, serverError }) {
  const [values, setValues] = useState(initialValues); const [errors, setErrors] = useState({});
  const inputClass = "mt-1 block w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200";
  function change(event) { const value = event.target.name === "paid" || event.target.name === "approvalRequired" ? event.target.value === "true" : event.target.value; setValues((current) => ({ ...current, [event.target.name]: value })); setErrors((current) => ({ ...current, [event.target.name]: "" })); }
  function submit(event) { event.preventDefault(); const next = {}; if (!values.name.trim()) next.name = "Type name is required."; if (!values.code.trim()) next.code = "Code is required."; setErrors(next); if (!Object.keys(next).length) onSubmit({ ...values, name: values.name.trim(), code: values.code.trim().toUpperCase() }); }
  return <form onSubmit={submit} noValidate className="overflow-hidden border border-slate-200 bg-white shadow-sm">{serverError && <div role="alert" className="border-b border-red-200 bg-red-50 px-5 py-3 text-sm text-red-700">{serverError}</div>}<div className="grid gap-x-6 gap-y-5 p-5 sm:grid-cols-2 sm:p-6"><Field label="Type name" name="name" value={values.name} onChange={change} error={errors.name} className={inputClass} /><Field label="Code" name="code" value={values.code} onChange={change} error={errors.code} className={inputClass} /><label className="text-sm font-medium text-slate-700 sm:col-span-2">Description <span className="font-normal text-slate-400">(optional)</span><textarea name="description" rows="4" value={values.description} onChange={change} className={inputClass} /></label><Select label="Leave payment" name="paid" value={String(values.paid)} onChange={change} className={inputClass} options={[["true", "Paid"], ["false", "Unpaid"]]} /><Select label="Approval required" name="approvalRequired" value={String(values.approvalRequired)} onChange={change} className={inputClass} options={[["true", "Yes"], ["false", "No"]]} /><Select label="Status" name="status" value={values.status} onChange={change} className={inputClass} options={[["Active", "Active"], ["Inactive", "Inactive"]]} /></div><div className="flex justify-end gap-3 border-t border-slate-200 bg-slate-50 px-5 py-4 sm:px-6"><button type="button" onClick={onCancel} className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancel</button><button type="submit" disabled={submitting} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-60">{submitting ? "Saving…" : "Save time off type"}</button></div></form>;
}
function Field({ label, name, value, onChange, error, className }) { return <label className="text-sm font-medium text-slate-700">{label} <span className="text-red-600">*</span><input name={name} value={value} onChange={onChange} className={className} aria-invalid={Boolean(error)} /><Error text={error} /></label>; }
function Select({ label, name, value, onChange, className, options }) { return <label className="text-sm font-medium text-slate-700">{label}<select name={name} value={value} onChange={onChange} className={className}>{options.map(([optionValue, text]) => <option key={optionValue} value={optionValue}>{text}</option>)}</select></label>; }
function Error({ text }) { return text ? <span className="mt-1 block text-xs text-red-600">{text}</span> : null; }
