import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getAllocationsByEmployee, calculateRemainingDays } from "../api/allocations.js";
import { getAttendanceByEmployee } from "../api/attendance.js";
import { getCurrentEmployee } from "../api/currentEmployee.js";
import { useAuth } from "../auth/AuthContext.jsx";
import { calculateRequestedDays, getTimeOffRequestsByEmployee } from "../api/timeOff.js";
import EmployeeAvatar from "../components/hr/EmployeeAvatar.jsx";
import AttendanceStatusBadge from "../components/hr/AttendanceStatusBadge.jsx";
import TimeOffStatusBadge from "../components/hr/TimeOffStatusBadge.jsx";

export default function MeHome() {
  const { employeeId } = useAuth();
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getCurrentEmployee(employeeId), getAttendanceByEmployee(employeeId), getAllocationsByEmployee(employeeId), getTimeOffRequestsByEmployee(employeeId)]).then(([employee, attendance, allocations, requests]) => setData({ employee, attendance, allocations, requests })).catch(() => setError("Your HR information could not be loaded.")); }, [employeeId]);
  if (error) return <State text={error} error />; if (!data) return <State text="Loading your workspace…" />;
  const { employee, attendance, allocations, requests } = data; const today = new Date().toISOString().slice(0, 10); const todayRecord = attendance.find((item) => item.date === today); const recentRequests = [...requests].sort((a, b) => b.startDate.localeCompare(a.startDate)).slice(0, 3);
  return <section><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Employee self-service</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">My HR workspace</h1><p className="mt-1 text-sm text-slate-600">View your profile, attendance, leave balances, and requests.</p></div>
    <div className="flex flex-wrap items-center gap-4 border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><EmployeeAvatar employee={employee} size="lg" /><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold text-slate-950">{employee.fullName}</h2><p className="mt-1 text-sm font-medium text-slate-500">{employee.employeeId}</p><p className="mt-2 text-sm text-slate-700">{employee.position} · {employee.department}</p></div><div className="flex flex-wrap gap-2"><Link to="/me/profile" className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">View profile</Link><Link to="/me/timeoff/new" className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800">Request time off</Link></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)]"><div className="space-y-5"><section className="border border-slate-200 bg-white shadow-sm"><Header title="Today's attendance" link="/me/attendance" /><div className="px-5 py-4">{todayRecord ? <div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{todayRecord.checkIn ? `Checked in at ${todayRecord.checkIn}` : "No check-in recorded"}</p><p className="mt-1 text-xs text-slate-500">{todayRecord.checkOut ? `Checked out at ${todayRecord.checkOut}` : "Checkout not recorded"}</p></div><AttendanceStatusBadge status={todayRecord.status} /></div> : <p className="text-sm text-slate-600">No attendance record for today.</p>}</div></section><section className="overflow-hidden border border-slate-200 bg-white shadow-sm"><Header title="My leave balances" /><table className="w-full text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-2.5">Leave type</th><th className="px-3 py-2.5">Allocated</th><th className="px-3 py-2.5">Used</th><th className="px-5 py-2.5">Remaining</th></tr></thead><tbody className="divide-y divide-slate-100">{allocations.filter((item) => item.status === "Active").map((item) => <tr key={item.id}><td className="px-5 py-3 font-medium text-slate-900">{item.timeOffTypeName}</td><td className="px-3 py-3 tabular-nums text-slate-600">{item.allocatedDays}</td><td className="px-3 py-3 tabular-nums text-slate-600">{item.usedDays}</td><td className="px-5 py-3 font-semibold tabular-nums text-emerald-700">{calculateRemainingDays(item)}</td></tr>)}</tbody></table></section></div>
      <section className="overflow-hidden border border-slate-200 bg-white shadow-sm"><Header title="Recent time off requests" link="/me/timeoff" /><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-y border-slate-200 bg-slate-50 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-2.5">Leave type</th><th className="px-3 py-2.5">Dates</th><th className="px-3 py-2.5">Duration</th><th className="px-5 py-2.5">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{recentRequests.map((item) => <tr key={item.id}><td className="px-5 py-3 font-medium text-slate-900">{item.timeOffTypeName}</td><td className="whitespace-nowrap px-3 py-3 text-slate-600">{item.startDate} – {item.endDate}</td><td className="px-3 py-3 tabular-nums text-slate-600">{calculateRequestedDays(item.startDate, item.endDate)} d</td><td className="px-5 py-3"><TimeOffStatusBadge status={item.status} /></td></tr>)}</tbody></table></div></section></div>
  </section>;
}
function Header({ title, link }) { return <div className="flex items-center justify-between px-5 py-3"><h2 className="text-sm font-semibold text-slate-950">{title}</h2>{link && <Link to={link} className="text-sm font-semibold text-blue-700 hover:underline">View all</Link>}</div>; } function State({ text, error }) { return <div className={`border p-10 text-center text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-slate-200 bg-white text-slate-600"}`}>{text}</div>; }
