import { useEffect, useMemo, useState } from "react";
import { calculateWorkedHours, getAttendanceByEmployee } from "../api/attendance.js";
import { useAuth } from "../auth/AuthContext.jsx";
import AttendanceStatusBadge from "../components/hr/AttendanceStatusBadge.jsx";

const dateFormatter = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" });
export default function MyAttendance() {
  const { employeeId } = useAuth();
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => { getAttendanceByEmployee(employeeId).then(setRecords).catch(() => setError("Your attendance could not be loaded.")).finally(() => setLoading(false)); }, [employeeId]);
  const filtered = useMemo(() => records.filter((item) => (!dateFrom || item.date >= dateFrom) && (!dateTo || item.date <= dateTo) && (!status || item.status === status)), [records, dateFrom, dateTo, status]); const clear = () => { setDateFrom(""); setDateTo(""); setStatus(""); };
  const control = "h-10 rounded-md border border-slate-300 bg-white px-3 text-sm text-slate-700 outline-none focus:border-slate-500 focus:ring-2 focus:ring-slate-200";
  return <section><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Employee self-service</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">My attendance</h1><p className="mt-1 text-sm text-slate-600">Review your recorded check-in and check-out history.</p></div><div className="overflow-hidden border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-2 border-b border-slate-200 bg-slate-50/70 p-3 sm:flex-row sm:px-5"><input aria-label="From date" title="From date" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className={control} /><input aria-label="To date" title="To date" type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className={control} /><select aria-label="Status" value={status} onChange={(event) => setStatus(event.target.value)} className={control}><option value="">All statuses</option><option>Present</option><option>Late</option><option>Absent</option><option>Missing Checkout</option><option>On Leave</option></select><button type="button" onClick={clear} disabled={!dateFrom && !dateTo && !status} className="h-10 px-3 text-left text-sm font-medium text-slate-600 disabled:opacity-40 sm:text-center">Clear filters</button></div>{loading ? <State text="Loading attendance…" /> : error ? <State text={error} error /> : !filtered.length ? <State text="No attendance records match your filters." /> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm sm:min-w-0"><thead className="border-b border-slate-200 bg-slate-50 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><tr>{["Date", "Check in", "Check out", "Worked hours", "Status"].map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((record) => { const worked = calculateWorkedHours(record.checkIn, record.checkOut); return <tr key={record.id} className="hover:bg-slate-50"><td className="px-5 py-3 font-medium text-slate-800">{dateFormatter.format(new Date(`${record.date}T00:00:00`))}</td><td className="px-5 py-3 tabular-nums text-slate-600">{record.checkIn || "—"}</td><td className="px-5 py-3 tabular-nums text-slate-600">{record.checkOut || "—"}</td><td className="px-5 py-3 font-semibold tabular-nums text-slate-800">{worked === null ? "—" : `${worked} h`}</td><td className="px-5 py-3"><AttendanceStatusBadge status={record.status} /></td></tr>; })}</tbody></table></div>}</div></section>;
}
function State({ text, error }) { return <div className={`px-6 py-14 text-center text-sm ${error ? "text-red-700" : "text-slate-600"}`}>{text}</div>; }
