import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthContext.jsx";
import { calculateRequestedDays, getTimeOffRequestsByEmployee } from "../api/timeOff.js";
import TimeOffStatusBadge from "../components/hr/TimeOffStatusBadge.jsx";

const dateFormatter = new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }); const date = (value) => dateFormatter.format(new Date(`${value}T00:00:00`));
export default function MyTimeOff() {
  const { employeeId } = useAuth();
  const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { getTimeOffRequestsByEmployee(employeeId).then(setRequests).catch(() => setError("Your time off requests could not be loaded.")).finally(() => setLoading(false)); }, [employeeId]);
  return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Employee self-service</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">My time off</h1><p className="mt-1 text-sm text-slate-600">Review your leave requests and their current status.</p></div><Link to="/me/timeoff/new" className="rounded-md bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800">Request time off</Link></div><div className="overflow-hidden border border-slate-200 bg-white shadow-sm">{loading ? <State text="Loading requests…" /> : error ? <State text={error} error /> : !requests.length ? <State text="You have no time off requests." /> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm md:min-w-0"><thead className="border-b border-slate-200 bg-slate-50 text-[11px] font-semibold uppercase tracking-wider text-slate-500"><tr>{["Leave type", "From", "To", "Duration", "Status"].map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{requests.map((request) => <tr key={request.id} className="hover:bg-slate-50"><td className="px-5 py-3 font-semibold text-slate-900">{request.timeOffTypeName}</td><td className="px-5 py-3 text-slate-600">{date(request.startDate)}</td><td className="px-5 py-3 text-slate-600">{date(request.endDate)}</td><td className="px-5 py-3 font-semibold tabular-nums text-slate-800">{calculateRequestedDays(request.startDate, request.endDate)} d</td><td className="px-5 py-3"><TimeOffStatusBadge status={request.status} /></td></tr>)}</tbody></table></div>}</div></section>;
}
function State({ text, error }) { return <div className={`px-6 py-14 text-center text-sm ${error ? "text-red-700" : "text-slate-600"}`}>{text}</div>; }
