import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getEmployeeById } from "../api/employees.js";
import { getTimeOffRequests, getTimeOffRequestsByEmployee } from "../api/timeOff.js";
import { getTimeOffTypes } from "../api/timeOffTypes.js";
import TimeOffFilterBar from "../components/hr/TimeOffFilterBar.jsx";
import TimeOffTable from "../components/hr/TimeOffTable.jsx";

export default function TimeOff() {
  const { employeeId } = useParams(); const [requests, setRequests] = useState([]); const [types, setTypes] = useState([]); const [employee, setEmployee] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [typeId, setTypeId] = useState(""); const [status, setStatus] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  useEffect(() => { setLoading(true); const request = employeeId ? Promise.all([getTimeOffRequestsByEmployee(employeeId), getTimeOffTypes(), getEmployeeById(employeeId)]) : Promise.all([getTimeOffRequests(), getTimeOffTypes(), Promise.resolve(null)]); request.then(([items, leaveTypes, person]) => { setRequests(items); setTypes(leaveTypes); setEmployee(person); }).catch((err) => setError(err.message || "Time off requests could not be loaded.")).finally(() => setLoading(false)); }, [employeeId]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return requests.filter((item) => (!query || item.employeeName.toLowerCase().includes(query) || item.employeeId.toLowerCase().includes(query) || item.id.toLowerCase().includes(query)) && (!typeId || item.timeOffTypeId === typeId) && (!status || item.status === status) && (!dateFrom || item.endDate >= dateFrom) && (!dateTo || item.startDate <= dateTo)); }, [requests, search, typeId, status, dateFrom, dateTo]);
  const clear = () => { setSearch(""); setTypeId(""); setStatus(""); setDateFrom(""); setDateTo(""); };
  return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Human Resources</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{employee ? `${employee.fullName}'s time off` : "Time off requests"}</h1><p className="mt-1 text-sm text-slate-600">Review employee leave requests and approval status.</p></div><div className="flex gap-2">{employee && <Link to={`/employees/${employee.id}`} className="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">View employee</Link>}<Link to={employee ? `/timeoff/new?employeeId=${employee.id}` : "/timeoff/new"} className="rounded-md bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800">New request</Link></div></div><div className="overflow-hidden border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-3"><p className="text-sm text-slate-600"><span className="font-semibold text-slate-950">{filtered.length}</span> {filtered.length === 1 ? "request" : "requests"}</p></div><TimeOffFilterBar {...{ search, typeId, types, status, dateFrom, dateTo }} onSearch={setSearch} onTypeId={setTypeId} onStatus={setStatus} onDateFrom={setDateFrom} onDateTo={setDateTo} onClear={clear} />{loading ? <State title="Loading time off requests…" /> : error ? <State title={error} error /> : !filtered.length ? <State title={requests.length ? "No requests match your filters." : "No time off requests found."} detail={requests.length ? "Try changing or clearing the current filters." : "Create a request to begin the approval workflow."} /> : <TimeOffTable requests={filtered} />}</div></section>;
}
function State({ title, detail, error }) { return <div className="px-6 py-16 text-center"><p className={`text-sm font-medium ${error ? "text-red-700" : "text-slate-700"}`}>{title}</p>{detail && <p className="mt-1 text-sm text-slate-500">{detail}</p>}</div>; }
