import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { approveTimeOffRequest, calculateRequestedDays, getTimeOffRequestById, refuseTimeOffRequest } from "../api/timeOff.js";
import TimeOffStatusBadge from "../components/hr/TimeOffStatusBadge.jsx";

const dateFormatter = new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }); const date = (value) => dateFormatter.format(new Date(`${value}T00:00:00`));
export default function TimeOffDetails() {
  const { id } = useParams(); const [request, setRequest] = useState(null); const [error, setError] = useState(""); const [updating, setUpdating] = useState(false);
  useEffect(() => { getTimeOffRequestById(id).then(setRequest).catch((err) => setError(err.message)); }, [id]);
  async function changeStatus(action) { setUpdating(true); setError(""); try { setRequest(await (action === "approve" ? approveTimeOffRequest(id) : refuseTimeOffRequest(id))); } catch (err) { setError(err.message || "Request status could not be updated."); } finally { setUpdating(false); } }
  if (error && !request) return <Message text={error} />; if (!request) return <Message text="Loading request…" hideLink />; const actionable = request.status === "Pending";
  return <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><Link to="/timeoff" className="text-sm font-medium text-slate-600 hover:text-slate-950">← Back to time off</Link><div className="flex flex-wrap gap-2"><Link to={`/employees/${request.employeeId}`} className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">View employee</Link><Link to={`/timeoff/${id}/edit`} className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit request</Link>{actionable && <><button type="button" disabled={updating} onClick={() => changeStatus("refuse")} className="rounded-md border border-red-200 bg-white px-4 py-2 text-sm font-semibold text-red-700 hover:bg-red-50 disabled:opacity-50">Refuse</button><button type="button" disabled={updating} onClick={() => changeStatus("approve")} className="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-50">Approve</button></>}</div></div>{error && <div className="mb-4 border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-200 p-5 sm:p-6"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Time off request · {request.id}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{request.employeeName}</h1><p className="mt-2 text-sm font-medium text-slate-700">{request.timeOffTypeName}</p></div><TimeOffStatusBadge status={request.status} /></header><div className="divide-y divide-slate-200 px-5 sm:px-6"><Info title="Request details" items={[["Employee", request.employeeName], ["Leave type", request.timeOffTypeName], ["Start date", date(request.startDate)], ["End date", date(request.endDate)], ["Duration", `${calculateRequestedDays(request.startDate, request.endDate)} days`], ["Status", request.status]]} /><Info title="Balance reference" items={[["Available balance", request.availableBalance === null ? "Not available" : `${request.availableBalance} days`]]} /><Info title="Reason" items={[["Reason", request.reason || "—"]]} /></div></div></section>;
}
function Info({ title, items }) { return <section className="py-6"><h2 className="mb-4 text-xs font-semibold uppercase tracking-wider text-slate-500">{title}</h2><dl className="grid gap-x-8 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([label, value]) => <div key={label}><dt className="text-xs font-medium text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{value}</dd></div>)}</dl></section>; } function Message({ text, hideLink }) { return <div className="border border-slate-200 bg-white p-10 text-center text-sm text-slate-600">{text}{!hideLink && <div className="mt-3"><Link to="/timeoff" className="font-semibold text-blue-700 hover:underline">Back to time off</Link></div>}</div>; }
